// =======================================================
// 1. TELEGRAM CONFIGURATION
// =======================================================
const BOTTOKEN = Deno.env.get("BOTTOKEN") || "BOTTOKEN_REQUIRED";
const CHATID = Deno.env.get("CHATID") || "CHATID_REQUIRED";
const TELEGRAMUPLOADURL = `https://api.telegram.org/bot${BOTTOKEN}/sendDocument`;

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
            };

            // ... (بقية الدوال المساعدة: getFileDownloadUrl و extractFileId تبقى كما هي)
            // (أفترض أنك قمت بتطبيقها من الرد السابق لضمان الاستخراج الصحيح)
            // ...

            // 🛑 دالة جديدة ومحسّنة لاستخراج file_id من استجابة Telegram (نكررها للتأكيد)
            function extractFileId(result) {
                if (!result) return null;

                    if (result.document && result.document.file_id) {
                            return result.document.file_id;
                                }
                                    if (result.video && result.video.file_id) {
                                            return result.video.file_id;
                                                }
                                                    if (result.photo && Array.isArray(result.photo) && result.photo.length > 0) {
                                                            const largestPhoto = result.photo.pop();
                                                                    if (largestPhoto.file_id) {
                                                                                 return largestPhoto.file_id;
                                                                                         }
                                                                                             }
                                                                                                 if (result.audio && result.audio.file_id) {
                                                                                                         return result.audio.file_id;
                                                                                                             }

                                                                                                                 return null;
                                                                                                                 }

                                                                                                                 async function getFileDownloadUrl(fileId, botToken) {
                                                                                                                     const getFileUrl = `https://api.telegram.org/bot${botToken}/getFile?file_id=${fileId}`;
                                                                                                                         
                                                                                                                             const getFileResponse = await fetch(getFileUrl);
                                                                                                                                 if (!getFileResponse.ok) {
                                                                                                                                         const errorText = await getFileResponse.text();
                                                                                                                                                 throw new Error(`Telegram API getFile Failed: ${getFileResponse.status} - ${errorText}`);
                                                                                                                                                     }

                                                                                                                                                         const fileData = await getFileResponse.json();

                                                                                                                                                             if (fileData.ok && fileData.result.file_path) {
                                                                                                                                                                     const filePath = fileData.result.file_path;
                                                                                                                                                                             return `https://api.telegram.org/file/bot${botToken}/${filePath}`;
                                                                                                                                                                                 } else {
                                                                                                                                                                                         throw new Error(`Telegram API getFile Error: ${fileData.description || 'Unknown error getting file path'}`);
                                                                                                                                                                                             }
                                                                                                                                                                                             }

                                                                                                                                                                                             // =======================================================
                                                                                                                                                                                             // 2. FILE UPLOAD HANDLER (POST /upload_file)
                                                                                                                                                                                             // =======================================================
                                                                                                                                                                                             async function handleUpload(req) {
                                                                                                                                                                                                 if (BOTTOKEN === "BOTTOKEN_REQUIRED") {
                                                                                                                                                                                                         return new Response(
                                                                                                                                                                                                                     JSON.stringify({ success: false, message: "Server Error: BOTTOKEN is not configured." }),
                                                                                                                                                                                                                                 { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                 try {
                                                                                                                                                                                                                                                         const formData = await req.formData();
                                                                                                                                                                                                                                                                 const file = formData.get('file');

                                                                                                                                                                                                                                                                         if (!file || typeof file === 'string') {
                                                                                                                                                                                                                                                                                     return new Response(
                                                                                                                                                                                                                                                                                                     JSON.stringify({ success: false, message: "No file part in the request (Field name must be 'file')." }),
                                                                                                                                                                                                                                                                                                                     { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                 const telegramFormData = new FormData();
                                                                                                                                                                                                                                                                                                                                                         telegramFormData.append('chat_id', CHATID);
                                                                                                                                                                                                                                                                                                                                                                 telegramFormData.append('caption', `Uploaded via Web App: ${file.name} (Type: ${file.type})`);
                                                                                                                                                                                                                                                                                                                                                                         telegramFormData.append('document', file, file.name); 
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                         console.log(`Attempting to upload file: ${file.name}, Size: ${file.size} bytes`); // 🛑 تسجيل محاولة الرفع

                                                                                                                                                                                                                                                                                                                                                                                                 // 1. إرسال الملف إلى Telegram 
                                                                                                                                                                                                                                                                                                                                                                                                         const telegramResponse = await fetch(TELEGRAMUPLOADURL, { method: 'POST', body: telegramFormData });

                                                                                                                                                                                                                                                                                                                                                                                                                 // 🛑 تسجيل استجابة Telegram
                                                                                                                                                                                                                                                                                                                                                                                                                         const telegramResponseClone = telegramResponse.clone();
                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!telegramResponse.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                     const errorText = await telegramResponse.text();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 console.error(`Telegram API Upload Failed (HTTP ${telegramResponse.status}):`, errorText); // 🛑 تسجيل الخطأ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             throw new Error(`Telegram API Upload Failed: ${telegramResponse.status} - ${errorText}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const data = await telegramResponseClone.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (data.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const result = data.result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const fileId = extractFileId(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!fileId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.error("Failed to extract file ID, keys received:", Object.keys(result).join(', '));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     throw new Error(`Telegram succeeded, but file ID extraction failed. Telegram response keys: ${Object.keys(result).join(', ')}.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const fileName = file.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // 2. الحصول على رابط التحميل المصحح
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const downloadUrl = await getFileDownloadUrl(fileId, BOTTOKEN);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             file_id: fileId, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 download_url: downloadUrl, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     filename: fileName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         message: `File uploaded successfully.`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // خطأ على مستوى JSON (data.ok === false)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.error(`Telegram API Error (data.ok=false):`, data.description);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 throw new Error(`Telegram API Error: ${data.description || 'Unknown error'}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.error("Server Error in handleUpload (CATCH BLOCK):", e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // نُرجع رسالة الخطأ الحقيقية من السيرفر
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     JSON.stringify({ success: false, message: e.message || "An unexpected server error occurred." }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // ... (بقية الراوتر تبقى كما هي) ...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Deno.serve(async (req) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const url = new URL(req.url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const pathname = url.pathname;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (req.method === 'OPTIONS') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return new Response(null, { status: 204, headers: corsHeaders });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (pathname.startsWith('/upload_file') && req.method === 'POST') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return handleUpload(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     JSON.stringify({ success: false, message: 'Invalid route.' }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });