// =======================================================
// 1. TELEGRAM CONFIGURATION
// =======================================================
const BOTTOKEN = Deno.env.get("BOTTOKEN") || "BOTTOKEN_REQUIRED";
const CHATID = Deno.env.get("CHATID") || "CHATID_REQUIRED";
const TELEGRAMUPLOADURL = `https://api.telegram.org/bot${BOTTOKEN}/sendDocument`;

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
            };

            // 🛑 تم إزالة دالة getFileDownloadUrl بالكامل لأنها تسبب الخطأ 400

            // دالة لاستخراج file_id (نحتفظ بها)
            function extractFileId(result) {
                if (!result) return null;

                    if (result.document && result.document.file_id) {
                            return result.document.file_id;
                                }
                                    if (result.video && result.video.file_id) {
                                            return result.video.file_id;
                                                }
                                                    if (result.photo && Array.isArray(result.photo) && result.photo.length > 0) {
                                                            const largestPhoto = result.photo.pop();
                                                                    if (largestPhoto.file_id) {
                                                                                 return largestPhoto.file_id;
                                                                                         }
                                                                                             }
                                                                                                 if (result.audio && result.audio.file_id) {
                                                                                                         return result.audio.file_id;
                                                                                                             }

                                                                                                                 return null;
                                                                                                                 }

                                                                                                                 // =======================================================
                                                                                                                 // 2. FILE UPLOAD HANDLER (POST /upload_file)
                                                                                                                 // =======================================================
                                                                                                                 async function handleUpload(req) {
                                                                                                                     if (BOTTOKEN === "BOTTOKEN_REQUIRED") {
                                                                                                                             return new Response(
                                                                                                                                         JSON.stringify({ success: false, message: "Server Error: BOTTOKEN is not configured." }),
                                                                                                                                                     { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                             );
                                                                                                                                                                 }

                                                                                                                                                                     try {
                                                                                                                                                                             const formData = await req.formData();
                                                                                                                                                                                     const file = formData.get('file');

                                                                                                                                                                                             if (!file || typeof file === 'string') {
                                                                                                                                                                                                         return new Response(
                                                                                                                                                                                                                         JSON.stringify({ success: false, message: "No file part in the request (Field name must be 'file')." }),
                                                                                                                                                                                                                                         { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                     const telegramFormData = new FormData();
                                                                                                                                                                                                                                                                             telegramFormData.append('chat_id', CHATID);
                                                                                                                                                                                                                                                                                     telegramFormData.append('caption', `Uploaded via Web App: ${file.name}`);
                                                                                                                                                                                                                                                                                             telegramFormData.append('document', file, file.name); 

                                                                                                                                                                                                                                                                                                     // 1. إرسال الملف إلى Telegram 
                                                                                                                                                                                                                                                                                                             const telegramResponse = await fetch(TELEGRAMUPLOADURL, { method: 'POST', body: telegramFormData });

                                                                                                                                                                                                                                                                                                                     if (!telegramResponse.ok) {
                                                                                                                                                                                                                                                                                                                                 const errorText = await telegramResponse.text();
                                                                                                                                                                                                                                                                                                                                             throw new Error(`Telegram API Upload Failed (Status ${telegramResponse.status}): ${errorText}`);
                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                             const data = await telegramResponse.json();

                                                                                                                                                                                                                                                                                                                                                                     if (data.ok) {
                                                                                                                                                                                                                                                                                                                                                                                 const result = data.result;
                                                                                                                                                                                                                                                                                                                                                                                             const fileId = extractFileId(result);
                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                     if (!fileId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                     throw new Error(`Telegram succeeded, but file ID extraction failed.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const fileName = file.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // 🛑 لم نعد نطلب downloadUrl من Telegram
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const downloadUrl = `https://api.telegram.org/file/bot${BOTTOKEN}/GET_FILE_PATH_FAILED_BUT_SAVED`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             file_id: fileId, // ✅ هذا هو المعرف الذي سنعتمد عليه
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 download_url: downloadUrl, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     filename: fileName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         message: `File uploaded successfully.`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         throw new Error(`Telegram API Error: ${data.description || 'Unknown error'}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // ... (تسجيل الخطأ)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 JSON.stringify({ success: false, message: e.message || "An unexpected server error occurred." }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // =======================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // 3. MAIN ROUTER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // =======================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Deno.serve(async (req) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const url = new URL(req.url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const pathname = url.pathname;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (req.method === 'OPTIONS') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return new Response(null, { status: 204, headers: corsHeaders });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (pathname.startsWith('/upload_file') && req.method === 'POST') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return handleUpload(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 JSON.stringify({ success: false, message: 'Invalid route.' }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });