// =======================================================
// 1. TELEGRAM CONFIGURATION
// =======================================================
const BOTTOKEN = Deno.env.get("BOTTOKEN") || "BOTTOKEN_REQUIRED";
const CHATID = Deno.env.get("CHATID") || "CHATID_REQUIRED";
const TELEGRAMUPLOADURL = `https://api.telegram.org/bot${BOTTOKEN}/sendDocument`;

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
            };

            // دالة مساعدة للحصول على المسار (file_path) وبناء رابط التحميل الصحيح
            async function getFileDownloadUrl(fileId, botToken) {
                const getFileUrl = `https://api.telegram.org/bot${botToken}/getFile?file_id=${fileId}`;
                    
                        const getFileResponse = await fetch(getFileUrl);
                            if (!getFileResponse.ok) {
                                    const errorText = await getFileResponse.text();
                                            throw new Error(`Telegram API getFile Failed: ${getFileResponse.status} - ${errorText}`);
                                                }

                                                    const fileData = await getFileResponse.json();

                                                        if (fileData.ok && fileData.result.file_path) {
                                                                const filePath = fileData.result.file_path;
                                                                        return `https://api.telegram.org/file/bot${botToken}/${filePath}`;
                                                                            } else {
                                                                                    throw new Error(`Telegram API getFile Error: ${fileData.description || 'Unknown error getting file path'}`);
                                                                                        }
                                                                                        }

                                                                                        // 🛑 دالة جديدة ومحسّنة: تستخرج file_id من أي نوع من أنواع استجابة Telegram
                                                                                        function extractFileId(result) {
                                                                                            if (!result) return null;

                                                                                                // 1. تحقق من المستند العام (Document - الأكثر شيوعاً لـ sendDocument)
                                                                                                    if (result.document && result.document.file_id) {
                                                                                                            return result.document.file_id;
                                                                                                                }
                                                                                                                    // 2. تحقق من الفيديو (Video)
                                                                                                                        if (result.video && result.video.file_id) {
                                                                                                                                return result.video.file_id;
                                                                                                                                    }
                                                                                                                                        // 3. تحقق من الصوتيات (Audio/Voice)
                                                                                                                                            if (result.audio && result.audio.file_id) {
                                                                                                                                                    return result.audio.file_id;
                                                                                                                                                        }
                                                                                                                                                            if (result.voice && result.voice.file_id) {
                                                                                                                                                                    return result.voice.file_id;
                                                                                                                                                                        }
                                                                                                                                                                            // 4. تحقق من الصور (Photo - array of sizes)
                                                                                                                                                                                if (result.photo && Array.isArray(result.photo) && result.photo.length > 0) {
                                                                                                                                                                                        // نأخذ file_id لأكبر نسخة من الصورة (عادةً الأخيرة في المصفوفة)
                                                                                                                                                                                                const largestPhoto = result.photo.pop();
                                                                                                                                                                                                        if (largestPhoto.file_id) {
                                                                                                                                                                                                                     return largestPhoto.file_id;
                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                     return null;
                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                     // =======================================================
                                                                                                                                                                                                                                     // 2. FILE UPLOAD HANDLER (POST /upload_file)
                                                                                                                                                                                                                                     // =======================================================
                                                                                                                                                                                                                                     async function handleUpload(req) {
                                                                                                                                                                                                                                         if (BOTTOKEN === "BOTTOKEN_REQUIRED") {
                                                                                                                                                                                                                                                 return new Response(
                                                                                                                                                                                                                                                             JSON.stringify({ success: false, message: "Server Error: BOTTOKEN is not configured." }),
                                                                                                                                                                                                                                                                         { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                         try {
                                                                                                                                                                                                                                                                                                 const formData = await req.formData();
                                                                                                                                                                                                                                                                                                         const file = formData.get('file');

                                                                                                                                                                                                                                                                                                                 if (!file || typeof file === 'string') {
                                                                                                                                                                                                                                                                                                                             return new Response(
                                                                                                                                                                                                                                                                                                                                             JSON.stringify({ success: false, message: "No file part in the request (Field name must be 'file')." }),
                                                                                                                                                                                                                                                                                                                                                             { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                         const telegramFormData = new FormData();
                                                                                                                                                                                                                                                                                                                                                                                                 telegramFormData.append('chat_id', CHATID);
                                                                                                                                                                                                                                                                                                                                                                                                         telegramFormData.append('caption', `Uploaded via Web App: ${file.name}`);
                                                                                                                                                                                                                                                                                                                                                                                                                 telegramFormData.append('document', file, file.name); 

                                                                                                                                                                                                                                                                                                                                                                                                                         // 1. إرسال الملف إلى Telegram 
                                                                                                                                                                                                                                                                                                                                                                                                                                 const telegramResponse = await fetch(TELEGRAMUPLOADURL, { method: 'POST', body: telegramFormData });
                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!telegramResponse.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                     const errorText = await telegramResponse.text();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 throw new Error(`Telegram API Upload Failed: ${telegramResponse.status} - ${errorText}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const data = await telegramResponse.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (data.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const result = data.result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // 🛑 استخدام الدالة المحسّنة لاستخراج file_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const fileId = extractFileId(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (!fileId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // نُرجع رسالة خطأ مفيدة جداً في حالة الفشل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 throw new Error(`Telegram succeeded, but file ID extraction failed. Telegram may have returned an unexpected structure. Response keys received: ${Object.keys(result).join(', ')}.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const fileName = file.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // 2. الحصول على رابط التحميل المصحح
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const downloadUrl = await getFileDownloadUrl(fileId, BOTTOKEN);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         file_id: fileId, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             download_url: downloadUrl, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 filename: fileName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     message: `File uploaded successfully.`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     throw new Error(`Telegram API Error: ${data.description || 'Unknown error'}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         console.error("Server Error in handleUpload:", e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             JSON.stringify({ success: false, message: e.message || "An unexpected server error occurred." }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // =======================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // 3. MAIN ROUTER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // =======================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Deno.serve(async (req) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const url = new URL(req.url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const pathname = url.pathname;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (req.method === 'OPTIONS') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return new Response(null, { status: 204, headers: corsHeaders });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (pathname.startsWith('/upload_file') && req.method === 'POST') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return handleUpload(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             JSON.stringify({ success: false, message: 'Invalid route.' }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });